syntax on

set nocompatible
filetype off

colorscheme slate

set expandtab
set shiftwidth=2
set tabstop=2
set number
set autoindent
set relativenumber

command W w
command Q q
command WQ wq
command Wq wq
