#!/bin/sh

# These the are places where sublime is installed by default
SUBLIME2_MAC="$HOME/Library/Application Support/Sublime Text 2/Packages/User/"
SUBLIME3_MAC="$HOME/Library/Application Support/Sublime Text 3/Packages/User/"

SUBLIME2_UBUNTU="$HOME/.config/sublime-text-2/Packages/User"
SUBLIME3_UBUNTU="$HOME/.config/sublime-text-3/Packages/User"

# Copy all the snippets to those directories
cp Other/*.tmTheme Tomorrow_themes/*.tmTheme "${SUBLIME2_MAC}" 2> /dev/null
cp Other/*.tmTheme Tomorrow_themes/*.tmTheme "${SUBLIME3_MAC}" 2> /dev/null

cp Other/*.tmTheme Tomorrow_themes/*.tmTheme "${SUBLIME2_UBUNTU}" 2> /dev/null
cp Other/*.tmTheme Tomorrow_themes/*.tmTheme "${SUBLIME3_UBUNTU}" 2> /dev/null

echo "\nPlaced new Color-Schemes into Sublime!\n"
echo "Now to change the color scheme do: \n\tPreferences->Settings - More -> Syntax Specific User"
echo "
Then enter this code for which ever color scheme you wish:
{
	\"color_scheme\" : \"Packages/User/Neon.tmTheme\"
}
"
